In [1]:
import read_write_file as rwf
import detectEnglish as det_eng
import random

In [2]:
#Caesar шифрование одного числа
def encrypt(m, key):
    c = (m + key) % 256
    return c

In [3]:
#Caesar дешифрование одного числа
def decrypt(m, key):
    c = (m - key) % 256
    return c

In [4]:
#Шифрование массива чисел
def encrypt_data(data, key):
    cypher_data = []
    for m in data:
        c = encrypt(m, key)
        cypher_data.append(c)
    return cypher_data

In [5]:
#Дешифрование массива чисел
def decrypt_data(data_c, key):
    data = []
    for c in data_c:
        m = decrypt(c, key)
        data.append(m)
    return data

In [6]:
#main1 - Первый main для тестов функций
def main1():
    m = 24
    key = 37
    c = encrypt(m, key)
    print('c =', c)
    m1 = decrypt(c, key)
    print('m1 =', m1)
    data = [34, 67, 123, 79, 201]
    encrypt_data_arr = encrypt_data(data, key)
    print('encrypt_data =', encrypt_data_arr)
    decrypt_data_arr = decrypt_data(encrypt_data_arr, key)
    print('decrypt_data =', decrypt_data_arr)

In [7]:
main1()

c = 61
m1 = 24
encrypt_data = [71, 104, 160, 116, 238]
decrypt_data = [34, 67, 123, 79, 201]


In [8]:
#main2 - шифруем файл
import read_write_file as rwf
def main2():
    data = rwf.read_data_1byte('f1.txt')
    print('data=', data[0:15])
    encrypt_data_arr = encrypt_data(data, key=67)
    print('encrypt_data =', encrypt_data_arr[0:15])
    txt = ''.join([chr(s) for s in encrypt_data_arr[0:15]])
    print('encrypt_text =', txt)
    rwf.write_data_1byte('f1_encrypt.txt', encrypt_data_arr)

In [9]:
main2()

data= [72, 101, 32, 119, 97, 115, 32, 97, 32, 98, 117, 114, 108, 121, 32]
encrypt_data = [139, 168, 99, 186, 164, 182, 99, 164, 99, 165, 184, 181, 175, 188, 99]
encrypt_text = ¨cº¤¶c¤c¥¸µ¯¼c


In [10]:
#main2_5 - дешифруем файл
def main2_5():
    encrypt_data_arr = rwf.read_data_1byte('f1_encrypt.txt')
    print('encrypt_data =', encrypt_data_arr[0:15])
    decrypt_data_arr = decrypt_data(encrypt_data_arr, key=67)
    print('decrypt_data =', decrypt_data_arr[0:15])
    txt = ''.join([chr(s) for s in decrypt_data_arr[0:15]])
    print('decrypt_data =', txt)
    rwf.write_data_1byte('f1_decrypt.txt', decrypt_data_arr)

    

In [11]:
main2_5()

encrypt_data = [139, 168, 99, 186, 164, 182, 99, 164, 99, 165, 184, 181, 175, 188, 99]
decrypt_data = [72, 101, 32, 119, 97, 115, 32, 97, 32, 98, 117, 114, 108, 121, 32]
decrypt_data = He was a burly 


In [12]:
#main3 
def main3():
    encrypt_data_arr = rwf.read_data_1byte('f1_encrypt.txt')
    print('encrypt_data =', encrypt_data_arr[0:15])
    for k in range(256):
        decrypt_data_arr = decrypt_data(encrypt_data_arr[0:15], key=k)
        txt = ''.join([chr(s) for s in decrypt_data_arr])
        print('decrypt_data =', txt)
        is_english = det_eng.isEnglish(txt)
        if (is_english):
            print("Decrypt k is ", k)
            break

In [13]:
main3()

encrypt_data = [139, 168, 99, 186, 164, 182, 99, 164, 99, 165, 184, 181, 175, 188, 99]
decrypt_data = ¨cº¤¶c¤c¥¸µ¯¼c
decrypt_data = §b¹£µb£b¤·´®»b
decrypt_data = ¦a¸¢´a¢a£¶³­ºa
decrypt_data = ¥`·¡³`¡`¢µ²¬¹`
decrypt_data = ¤_¶ ²_ _¡´±«¸_
decrypt_data = £^µ±^^ ³°ª·^
decrypt_data = ¢]´°]]²¯©¶]
decrypt_data = ¡\³¯\\±®¨µ\
decrypt_data =  [²®[[°­§´[
decrypt_data = Z±­ZZ¯¬¦³Z
decrypt_data = Y°¬YY®«¥²Y
decrypt_data = X¯«XX­ª¤±X
decrypt_data = W®ªWW¬©£°W
decrypt_data = ~V­©VV«¨¢¯V
decrypt_data = }U¬¨UUª§¡®U
decrypt_data = |T«§TT©¦ ­T
decrypt_data = {Sª¦SS¨¥¬S
decrypt_data = zR©¥RR§¤«R
decrypt_data = yQ¨¤QQ¦£ªQ
decrypt_data = xP§£PP¥¢©P
decrypt_data = wO¦¢OO¤¡¨O
decrypt_data = vN¥¡NN£ §N
decrypt_data = uM¤ MM¢¦M
decrypt_data = tL£LL¡¥L
decrypt_data = sK¢KK ¤K
decrypt_data = rJ¡JJ£J
decrypt_data = qI II¢I
decrypt_data = pHHH¡H
decrypt_data = oGGG G
decrypt_data =

In [14]:
#main4 - работа с изображениями
def main4():
    data = rwf.read_data_1byte('f2.png')
    print(data)
    encrypt_data_arr = encrypt_data(data, key=143)
    rwf.write_data_1byte('f2_encrypt.png', encrypt_data_arr)

In [15]:
main4()

[137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 213, 0, 0, 0, 234, 8, 6, 0, 0, 0, 53, 108, 0, 251, 0, 0, 0, 1, 115, 82, 71, 66, 0, 174, 206, 28, 233, 0, 0, 0, 4, 103, 65, 77, 65, 0, 0, 177, 143, 11, 252, 97, 5, 0, 0, 0, 9, 112, 72, 89, 115, 0, 0, 14, 195, 0, 0, 14, 195, 1, 199, 111, 168, 100, 0, 0, 255, 165, 73, 68, 65, 84, 120, 94, 236, 189, 5, 64, 85, 233, 246, 255, 237, 173, 185, 211, 99, 43, 221, 72, 41, 210, 221, 173, 40, 40, 98, 35, 118, 129, 162, 116, 135, 32, 32, 34, 32, 221, 221, 42, 118, 183, 99, 205, 204, 157, 238, 176, 187, 3, 65, 68, 157, 239, 187, 214, 115, 56, 14, 227, 245, 214, 251, 255, 221, 185, 51, 247, 186, 102, 150, 123, 159, 125, 54, 251, 236, 120, 62, 123, 197, 83, 125, 240, 82, 254, 5, 121, 10, 252, 216, 45, 81, 90, 255, 145, 254, 125, 68, 250, 144, 244, 65, 47, 229, 207, 188, 157, 191, 199, 143, 143, 105, 215, 78, 224, 73, 187, 88, 62, 161, 77, 93, 61, 223, 211, 55, 226, 179, 216, 79, 8, 31, 159, 149, 190, 145, 42, 111, 251, 153, 190, 14

Задание 1 - расшифровать зашифрованное изображение шифром Цезаря (ключ 143)

In [16]:
def find_key_png(_encrypt_data):
    for k in range(256):
        decrypt_data_arr = decrypt_data(_encrypt_data, key=k)
        x1 = hex(decrypt_data_arr[0])[2:]
        x2 = hex(decrypt_data_arr[1])[2:]
        if (x1 == '89' and x2 == '50'):
            print("Decrypt k is", k)
            return k        
    return -1


def ex1():
    data = rwf.read_data_1byte('f2_encrypt.png')
    k = find_key_png(data[0:2])
    if (k == -1):
        print("Key isn't found. Error!")
        return 
    decrypt_data_arr = decrypt_data(data, key=k)
    print('decrypt_data =', decrypt_data_arr[0:15])
    rwf.write_data_1byte('f2_decrypt.png', decrypt_data_arr)


In [17]:
ex1()

Decrypt k is

 143
decrypt_data = [137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68]


Задание 2 (тк Вариант 1, тк я 11 в списке)

In [18]:
def ex2():
    encrypt_data_arr = rwf.read_data_1byte('t3_caesar_c_all.txt')
    print('encrypt_data =', encrypt_data_arr[0:15])
    for k in range(256):
        decrypt_data_arr = decrypt_data(encrypt_data_arr, key=k)
        txt = ''.join([chr(s) for s in decrypt_data_arr])
        print('decrypt_data =', txt)
        is_english = det_eng.isEnglish(txt)
        if (is_english):
            print("Decrypt k is ", k)
            rwf.write_data_1byte('t3_caesar_c_all_decrypt.txt', decrypt_data_arr)
            break

In [19]:
ex2()

encrypt_data = [169, 215, 246, 246, 249, 167, 250, 246, 252, 243, 168, 169, 167, 202, 232]
decrypt_data = ©×ööù§úöüó¨©§Êèôðóóè§÷ùìúìõûó §þìõû§öõ§¯Ð§òõìþ§ûïì §ïèë§èóó§éììõ§óööòðõî§èû§ôì§ðõ§ûïì§ôìèõ§ûðôì°³§©ïì§ðú§úö§ýìù §úûùèõîì¨§Þöüóë§èõ öõì§éìóðìýì§ûïèû§þïìõ§Ûöô®ú§þðíì§ëðìë³§ïì§èêûüèóó §êöüóë§õöû§éì§ðõëüêìë§ûö§úìì§ûïì§ðô÷öùûèõêì§öí§ûïì§êïðóëùìõ®ú§ïèýðõî§ûïì§ëìì÷ìúû§öí§ûùðôôðõîú§ûö§ûïìðù§ôöüùõðõîÆ§®Îööë§Óöùë¨®§úè ú§ïì³§®Êèôðóóè³§þïèû§êèõ§ðû§úðîõðí §úö§óöõî§èú§ûïì§÷ööù§éìùìèýìë§óðûûóì§ûïðõîú§èùì§ðõ§éóèêòÆ®§Úö§óðòì§Ôèûûïìþ¨§Ûïì§ðëìè¨©©Îööë§÷öðõûú§ðõ§ïðô³§îööë§÷öðõûú§ðõ§ïðô³©§úèðë§Êöüúðõ§Ùè ôöõëÂ§©Ïìèýìõ§íöùéðë§Ð§úïöüóë§ëìõ §îööë§÷öðõûú§ðõ§ïðôÂ§éüû§ïì§õìýìù§ïèë³§èõë§ïì§õìýìù§þðóó§ïèýì³§èõ §úìõúì§öí§ûïì§÷ùö÷ùðìûðìúµ©©àöü§òõöþ§Ð§þèú§öéóðîìë³©§úèðë§Êèôðóóè³§©Ð§þèú§öéóðîìë§ûö§éì§íðùôµ§Ð§úèðë³§®Ðû§ÞÐÓÓ§ÕÖÛ§ËÖ³§íöù§ûïì§êùìëðû§öí§ûïì§íèôðó µ®§Ð§ûöóë§ïðô§ûïèû³§þðûïöüû§ëìì÷§ûùðôôðõîú³§ûïì§íèôðó §þèú§ëðúîùèêìëµ§Ð§êùðìë§èéöüû§ðû§íùöô§éùìèòíèúû§ûðóó§ëðõõìùµ§Ð§ðõñüùìë§ô §ëðîìúûðöõµ§Èõë§èû§óèúû§

Задание 4. Моноалфавитный шифр

In [20]:
from os import write


def ex4():
    k=[179, 109, 157, 182, 126, 141, 251, 220, 169, 237, 188, 131, 207, 22, 32, 242, 208, 68, 216, 170, 249, 199, 44,
        198, 206, 8, 148, 197, 136, 195, 159, 98, 175, 53, 123, 212, 233, 150, 6, 243, 38, 79, 156, 153, 2, 134, 47, 215, 102,
        15, 57, 110, 236, 24, 184, 72, 137, 113, 171, 70, 161, 64, 252, 247, 49, 103, 105, 138, 119, 213, 87, 130, 203, 90,
        167, 238, 231, 116, 78, 86, 173, 250, 200, 239, 178, 97, 114, 94, 166, 142, 104, 31, 75, 89, 106, 56, 128, 69, 164, 67,
        26, 228, 61, 181, 125, 227, 54, 96, 168, 107, 17, 14, 37, 190, 219, 211, 121, 112, 35, 18, 143, 158, 193, 129, 71, 23,
        101, 191, 41, 241, 82, 201, 223, 120, 59, 177, 58, 63, 151, 42, 36, 183, 226, 127, 172, 202, 84, 132, 3, 45, 73, 30,
        235, 50, 189, 4, 1, 43, 221, 205, 83, 232, 46, 147, 93, 192, 124, 244, 12, 21, 80, 55, 160, 145, 245, 209, 88, 204, 176,
        13, 253, 11, 99, 165, 140, 19, 224, 111, 27, 185, 65, 62, 16, 163, 210, 115, 217, 34, 92, 187, 152, 155, 108, 5, 122,
        229, 174, 118, 162, 95, 100, 7, 66, 29, 230, 144, 149, 52, 9, 91, 117, 214, 76, 48, 33, 194, 254, 10, 234, 218, 40, 133,
        196, 139, 135, 240, 60, 25, 225, 85, 255, 246, 51, 28, 146, 74, 222, 186, 39, 77, 0, 20, 180, 154, 81, 248]
    encrypt_data_arr = rwf.read_data_1byte('c3_subst_c_all.png')
    decrypt_data_arr = []
    for c in encrypt_data_arr:
        decrypt_data_arr.append(k.index(c))
    rwf.write_data_1byte('c3_subst_c_all_decrypt.png', decrypt_data_arr)


In [21]:
ex4()

Задание 5.
Расшифровать файл ff2_affine_c_all.bmp. Шифр аффинный. a=167, b=
35. Зашифровать, оставив первые 50 байт без изменения. Сравнить с
оригинальным изображением.

In [37]:
def gcd(a, b):
    while a != 0:
        a, b = b % a, a
    return b


def findModInverse(a, m):
    # Returns the modular inverse of a % m, which is
    # the number x such that a*x % m = 1
    if gcd(a, m) != 1:
        return None # no mod inverse if a & m aren't relatively prime
    # Calculate using the Extended Euclidean Algorithm:
    u1, u2, u3 = 1, 0, a
    v1, v2, v3 = 0, 1, m
    while v3 != 0:
        q = u3 // v3 # // is the integer division operator
        v1, v2, v3, u1, u2, u3 = (u1 - q * v1), (u2 - q * v2), (u3 - q * v3), v1, v2, v3
    return u1 % m


def ex5():
    a = 19
    b = 236
    l = 256

    a_1 = findModInverse(a, l)
    if (a_1 == None):
        print('Error! findModInverse error!', a)
        return

    encrypt_data_arr = rwf.read_data_1byte('ff2_affine_c_all.bmp')
    decrypt_data_arr = []
    for e in encrypt_data_arr:
        m = (e - b) * a_1 % l
        decrypt_data_arr.append(m)
    rwf.write_data_1byte('ff2_affine_c_all_decrypt.bmp', decrypt_data_arr)

    data_arr = rwf.read_data_1byte('ff2_affine_c_all_decrypt.bmp')
    crypt_arr = []
    for i in range(50):
        crypt_arr.append(data_arr[i])
    for i in range(50, len(data_arr)):
        e = (data_arr[i] + b) * a % l
        crypt_arr.append(e)
    rwf.write_data_1byte('ff2_affine_c_all_crypt50.bmp', crypt_arr)




In [36]:
ex5()

Задание 6. 
Дешифровать файл text10_affine_c_all.txt. Шифр аффинный.
Подсчитать сколько перебрали вариантов ключей.

In [24]:
def ex6():
    a = 1
    b = 1
    l = 256
    count = 0
    for a in range(1000):
        a_1 = findModInverse(a, l)
        if (a_1 == None):
            count += 1
            continue
        for b in range(1000):
            encrypt_data_arr = rwf.read_data_1byte('text10_affine_c_all.txt')
            decrypt_data_arr = []
            for e in encrypt_data_arr:
                m = ((e - b) * a_1) % l
                decrypt_data_arr.append(m)
            txt = ''.join([chr(s) for s in decrypt_data_arr])
            # print('decrypt_data =', txt)
            is_english = det_eng.isEnglish(txt)
            count += 1
            if (is_english):
                print("Decrypted with a =", a, "and b =", b)
                print("Count =", count)
                print("True count =", a * b)
                rwf.write_data_1byte('text10_affine_c_all_decrypt.txt', decrypt_data_arr)
                return count

In [25]:
ex6()

Decrypted with a = 29 and b = 116
Count = 14132
True count = 3364


14132

Задание 8. Шифр Вижинера. Ключ magistr

In [26]:
def ex8():
    encrypt_data_arr = rwf.read_data_1byte('im6_vigener_c_all.bmp')
    key = 'magistr'
    k = [ord(s) for s in key]
    decrypt_data_arr = []
    j = 0 #перебор ключа
    l = 256 #размер алфавита
    for i in range(len(encrypt_data_arr)):
        j = j % len(k)
        m = (encrypt_data_arr[i] - k[j]) % l
        decrypt_data_arr.append(m)
        j += 1
    rwf.write_data_1byte('im6_vigener_c_all_decrypt.bmp', decrypt_data_arr)

    data_arr = rwf.read_data_1byte('im6_vigener_c_all_decrypt.bmp')
    crypt_arr = []
    j = 0
    for i in range(50):
        crypt_arr.append(data_arr[i])
    for i in range(50, len(data_arr)):
        j = j % len(k)
        e = (data_arr[i] + k[j]) % l
        crypt_arr.append(e)
        j += 1
    rwf.write_data_1byte('im6_vigener_c_all_crypt50.bmp', crypt_arr)

In [27]:
ex8()

Задание 9. Дешифровать text4_vigener_c.txt – зашифрованное шифром Вижинера
текстовое сообщение. Известно, что сообщение начинается со строки из
одних пробелов.

In [28]:
def ex9():
    encrypt_data_arr = rwf.read_data_1byte('text4_vigener_c_all.txt')
    key = 'student'
    k = [ord(s) for s in key]
    decrypt_data_arr = []
    j = 0 #перебор ключа
    l = 256 #размер алфавита
    for i in range(len(encrypt_data_arr)):
        j = j % len(k)
        m = (encrypt_data_arr[i] - k[j]) % l
        decrypt_data_arr.append(m)
        j += 1
    rwf.write_data_1byte('text4_vigener_c_all_decrypt.txt', decrypt_data_arr)

In [29]:
ex9()

Задание 10. housewives

In [30]:
# def ex10():
#     encrypt_data_arr = rwf.read_data_1byte('text4_vigener_c_all.txt')
#     key = 'housewives'
#     k = [ord(s) for s in key]
#     l = 256 #размер алфавита
#     for i in range(len(encrypt_data_arr)):
#         decrypt_data_arr = []
#         for j in range(len(k)):
#             m = (encrypt_data_arr[i] - k[j]) % l
#             decrypt_data_arr.append(m)
#         txt = ''.join([chr(s) for s in decrypt_data_arr])
#         print(txt)



def ex10():
    encrypt_data_arr = rwf.read_data_1byte('text4_vigener_c_all.txt')
    word = 'housewives'
    for i in range(0, len(encrypt_data_arr) - len(word)):
        key = ''
        for j in range(len(word)):
            key += chr((encrypt_data_arr[i+j] - ord(word[j]))%256)
            print(key)

In [31]:
ex10()

+
+%
+% 
+% 
+%  
+%  
+%  +
+%  +
+%  +/
+%  +/"
,
,&
,&
,&
,&)
,&)
,&)*
,&)*
,&)*0
,&)*0
-
-
-
-
-/
-/
-/+
-/+
-/+
-/+



!
!.
!.
!.,
!.,
!., 
!., 



 
 /
 /
 /
 /
 /)
 /)!
&
&%
&%
&%!
&%!0
&%!0
%!0
!0
/!0
/ 0
,
,$
,$
,$"
,$"
,$"
,$"%
,$"%
,$"%.
,$"%.!
+
+%
+% 
+% 
+%  
+%  
+%  +
+%  +
+%  +/
+%  +/"
,
,&
,&
,&
,&)
,&)
,&)*
,&)*
,&)*0
,&)*0
-
-
-
-
-/
-/
-/+
-/+
-/+
-/+



!
!.
!.
!.,
!.,
!., 
!., 



 
 /
 /
 /
 /
 /)
 /)!
&
&%
&%
&%!
&%!0
&%!0
%!0
!0
/!0
/!0
,
,$
,$
,$"
,$"
,$"
,$"%
,$"%
,$"%
,$"%
+
+%
+% 
+% 
+%  
+%  
+%  +
+%  +

+%  +

+%  +
N
,
,&
,&
,&
,&)
,&)
,&)
,&)
,&)\
,&)

Задание 11. Дешифровать файл (text1_vigener_c.txt) – зашифрованное шифром
Вижинера текстовое сообщение. Известно, что в сообщении присутствуют
слова it therefore.

In [32]:
def ex11():
    encrypt_data_arr = rwf.read_data_1byte('text1_vigener_c.txt')
    key = 'it therefore'
    k = [ord(s) for s in key]
    decrypt_data_arr = []
    j = 0 #перебор ключа
    l = 256 #размер алфавита
    for i in range(len(encrypt_data_arr)):
        j = j % len(k)
        m = (encrypt_data_arr[i] - k[j]) % l
        decrypt_data_arr.append(m)
        j += 1
    rwf.write_data_1byte('text1_vigener_c_decrypt.txt', decrypt_data_arr)

In [33]:
ex11()